version: '3.1'

services:
  bot:
    container_name: bot
    working_dir: /Happy.do_global
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "python bot.py"
    ports:
      - "0.0.0.0:8080:8080"
